name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update Rust
        run: rustup update

      - uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Build Page
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAGE_TOKEN }}
          publish_dir: ./build
